// Generated by gencpp from file ros_motor/angle.msg
// DO NOT EDIT!


#ifndef ROS_MOTOR_MESSAGE_ANGLE_H
#define ROS_MOTOR_MESSAGE_ANGLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_motor
{
template <class ContainerAllocator>
struct angle_
{
  typedef angle_<ContainerAllocator> Type;

  angle_()
    : angle(0)  {
    }
  angle_(const ContainerAllocator& _alloc)
    : angle(0)  {
  (void)_alloc;
    }



   typedef int32_t _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::ros_motor::angle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_motor::angle_<ContainerAllocator> const> ConstPtr;

}; // struct angle_

typedef ::ros_motor::angle_<std::allocator<void> > angle;

typedef boost::shared_ptr< ::ros_motor::angle > anglePtr;
typedef boost::shared_ptr< ::ros_motor::angle const> angleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_motor::angle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_motor::angle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_motor::angle_<ContainerAllocator1> & lhs, const ::ros_motor::angle_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_motor::angle_<ContainerAllocator1> & lhs, const ::ros_motor::angle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_motor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_motor::angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_motor::angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_motor::angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_motor::angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_motor::angle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_motor::angle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_motor::angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de62f7ef8463d5c42dacb6932cbd1470";
  }

  static const char* value(const ::ros_motor::angle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xde62f7ef8463d5c4ULL;
  static const uint64_t static_value2 = 0x2dacb6932cbd1470ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_motor::angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_motor/angle";
  }

  static const char* value(const ::ros_motor::angle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_motor::angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 angle\n"
;
  }

  static const char* value(const ::ros_motor::angle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_motor::angle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct angle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_motor::angle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_motor::angle_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<int32_t>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_MOTOR_MESSAGE_ANGLE_H
