// Generated by gencpp from file ros_serial/semes.msg
// DO NOT EDIT!


#ifndef ROS_SERIAL_MESSAGE_SEMES_H
#define ROS_SERIAL_MESSAGE_SEMES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_serial
{
template <class ContainerAllocator>
struct semes_
{
  typedef semes_<ContainerAllocator> Type;

  semes_()
    : temp(0.0)  {
    }
  semes_(const ContainerAllocator& _alloc)
    : temp(0.0)  {
  (void)_alloc;
    }



   typedef double _temp_type;
  _temp_type temp;





  typedef boost::shared_ptr< ::ros_serial::semes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_serial::semes_<ContainerAllocator> const> ConstPtr;

}; // struct semes_

typedef ::ros_serial::semes_<std::allocator<void> > semes;

typedef boost::shared_ptr< ::ros_serial::semes > semesPtr;
typedef boost::shared_ptr< ::ros_serial::semes const> semesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_serial::semes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_serial::semes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_serial::semes_<ContainerAllocator1> & lhs, const ::ros_serial::semes_<ContainerAllocator2> & rhs)
{
  return lhs.temp == rhs.temp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_serial::semes_<ContainerAllocator1> & lhs, const ::ros_serial::semes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_serial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_serial::semes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_serial::semes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_serial::semes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_serial::semes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_serial::semes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_serial::semes_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_serial::semes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1c666a4992d5d6108cc9173c68311b1d";
  }

  static const char* value(const ::ros_serial::semes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1c666a4992d5d610ULL;
  static const uint64_t static_value2 = 0x8cc9173c68311b1dULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_serial::semes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_serial/semes";
  }

  static const char* value(const ::ros_serial::semes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_serial::semes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 temp\n"
;
  }

  static const char* value(const ::ros_serial::semes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_serial::semes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.temp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct semes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_serial::semes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_serial::semes_<ContainerAllocator>& v)
  {
    s << indent << "temp: ";
    Printer<double>::stream(s, indent + "  ", v.temp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SERIAL_MESSAGE_SEMES_H
